exps = [
    "smi_cisplitmnist_fecnn",
    "smi_cisplitcifar10_feresnet",
    "smi_cisplitham8_feresnet",
    "smi_displitmnist_fecnn",
    "smi_displitcifar8_feresnet",
    "smi_displitham6_feresnet"
]
    
[[metrics]]
name = "Final average accuracy"
metametric = "final_average"
basemetric = "accuracy"
