exps = [
    "svi_cisplitmnist_fcnn",
    "svi_cisplitmnist_cnn",
    "svi_displitmnist_fcnn",
    "svi_displitmnist_cnn"
]
    
[[metrics]]
name = "Final average accuracy"
metametric = "final_average"
basemetric = "accuracy"
