exps = [
    "svi_cisplitmnist_fe1",
    "svi_cisplitcifar10_fe1",
    "svi_cisplitham8_fe1",
    "svi_displitmnist_fe1",
    "svi_displitcifar8_fe1",
    "svi_displitham6_fe1"
]
    
[[metrics]]
name = "Final average accuracy"
metametric = "final_average"
basemetric = "accuracy"

[[metrics]]
name = "Continual uncertainty loss"
metametric = "msdsut1"
basemetric = "mne"
